### ISSUE TITLE
Cannot override default scrapePort

### ISSUE THREAD

**Issue by nimaafraz** [hyperledger-caliper/caliper-benchmarks#130]
I'm running Caliper locally and since the scrapePort for the workers' defaults in 3000, it conflicts with Grafana port (also 3000).
I tried to change it as follows:
```
monitors:
    transaction:
    - module: prometheus
    options:
      interval: 5
      scrapePort: 4000
```
But it did not seem to work as the scrapePort for the workers would still start from 300. For now I fixed the issue temporarily by changing the `/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/worker/tx-observers/prometheus-tx-observer.js,8157,1605195368000`:

```
        if (CaliperUtils.isForkedProcess()) {
            this.scrapePort += workerIndex+1;
        }
```

Well, it's not an ideal solution I guess.

**Comment by davidkel** [comment]
This doesn't appear to be relevant to caliper-benchmarks but a potential issue with caliper

**Comment by davidkel** [comment]
The problem is one of indentation, the options property is associated with the module, but in the above example the options is associated with the transaction property which is not correct. It should be
```
monitors:
    transaction:
    - module: prometheus
      options:
        interval: 5
        scrapePort: 4000
```
Then it will pick up the option values for the prometheus module
